import type { GalleryItem } from "@/types/gallery";

/**
 * Inspiration Library — données des photos de la galerie.
 *
 * TODO(CMS) : remplaçant temporaire en attendant un vrai CMS (Phase 7).
 * Pour ajouter un nouveau lot de photos : déposer les fichiers dans
 * public/images/gallery/, puis ajouter une entrée ici par photo.
 * Rien d'autre à modifier — la grille, les filtres et la visionneuse
 * s'adaptent automatiquement au nombre d'éléments.
 */
export const galleryItems: GalleryItem[] = [
  {
    id: "yacht-bow",
    image: "/images/gallery/yacht-bow.jpg",
    alt: "Mahogany deck and superstructure on a luxury motor yacht",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Deck planking, exterior cladding",
    finish: "Oiled, marine-grade sealed",
    setting: "Outdoor",
    commonDimensions: "20–25mm deck boards",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "corporate-boardroom",
    image: "/images/gallery/corporate-boardroom.jpg",
    alt: "Executive boardroom table and wall panelling in mahogany",
    category: "corporate-hq",
    species: "African Mahogany (Khaya)",
    application: "Boardroom table, wall panelling",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "38–50mm tabletop",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "bedroom-wardrobe",
    image: "/images/gallery/bedroom-wardrobe.jpg",
    alt: "Bedroom with built-in mahogany wardrobe and herringbone flooring",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Built-in wardrobe, wall panelling, herringbone flooring",
    finish: "Satin lacquer (joinery), oiled (flooring)",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom joinery",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "walk-in-closet",
    image: "/images/gallery/walk-in-closet.jpg",
    alt: "Walk-in closet with mahogany cabinetry and parquet flooring",
    category: "furniture",
    species: "African Mahogany (Khaya)",
    application: "Custom cabinetry, island unit, parquet flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom cabinetry",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "staircase-skylight",
    image: "/images/gallery/staircase-skylight.jpg",
    alt: "Modern mahogany staircase beneath an architectural skylight",
    category: "staircases",
    species: "African Mahogany (Khaya)",
    application: "Staircase treads, stringers, wall cladding",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "40–50mm treads",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "staircase-grand-hall",
    image: "/images/gallery/staircase-grand-hall.jpg",
    alt: "Grand mahogany staircase in a residential entrance hall",
    category: "staircases",
    species: "African Mahogany (Khaya)",
    application: "Staircase, handrail, door frames",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "40–50mm treads",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "living-room-fireplace",
    image: "/images/gallery/living-room-fireplace.jpg",
    alt: "Living room with full-height mahogany fireplace wall panelling",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Full-height wall panelling, coffee table",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "19–25mm panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "executive-office",
    image: "/images/gallery/executive-office.jpg",
    alt: "Executive office with coffered mahogany ceiling and built-in library",
    category: "corporate-hq",
    species: "African Mahogany (Khaya)",
    application: "Coffered ceiling, built-in shelving, executive desk",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom millwork",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "library-study",
    image: "/images/gallery/library-study.jpg",
    alt: "Private library with mahogany shelving and herringbone floor",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Built-in shelving, wall panelling, herringbone flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom shelving",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "staircase-modern-plant",
    image: "/images/gallery/staircase-modern-plant.jpg",
    alt: "Contemporary mahogany staircase with integrated lighting",
    category: "staircases",
    species: "African Mahogany (Khaya)",
    application: "Staircase treads, wall cladding",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "40–50mm treads",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "home-bar",
    image: "/images/gallery/home-bar.jpg",
    alt: "Home bar with mahogany shelving and marble countertop",
    category: "fine-dining",
    species: "African Mahogany (Khaya)",
    application: "Bar shelving, cabinetry, wall panelling",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom millwork",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "home-theater",
    image: "/images/gallery/home-theater.jpg",
    alt: "Private home theater with mahogany panelling and herringbone floor",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Wall panelling, herringbone flooring",
    finish: "Gloss lacquer (walls), oiled (floor)",
    setting: "Indoor",
    commonDimensions: "14mm flooring",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "luxury-bathroom",
    image: "/images/gallery/luxury-bathroom.jpg",
    alt: "Luxury bathroom with mahogany vanity cabinetry",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Vanity cabinetry",
    finish: "Marine-grade lacquer",
    setting: "Indoor",
    commonDimensions: "Custom cabinetry",
    durability: "High",
    moistureResistance: "Enhanced (wet-area finish)",
  },
  {
    id: "kitchen-island",
    image: "/images/gallery/kitchen-island.jpg",
    alt: "Modern kitchen with mahogany cabinetry and herringbone flooring",
    category: "furniture",
    species: "African Mahogany (Khaya)",
    application: "Kitchen cabinetry, island unit, herringbone flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom cabinetry",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "living-room-chandelier",
    image: "/images/gallery/living-room-chandelier.jpg",
    alt: "Formal living room with mahogany wall panelling and parquet floor",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Wall panelling, window frames, parquet flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, 19–25mm panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },

  // --- Lot 2 ---
  {
    id: "yacht-cabin-sunset",
    image: "/images/gallery/yacht-cabin-sunset.jpg",
    alt: "Yacht master cabin with mahogany panelling and sunset ocean view",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Cabin panelling, joinery, flooring",
    finish: "Marine-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom marine joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "outdoor-kitchen-pergola",
    image: "/images/gallery/outdoor-kitchen-pergola.jpg",
    alt: "Outdoor kitchen and dining pergola in mahogany",
    category: "decking",
    species: "African Mahogany (Khaya)",
    application: "Pergola structure, outdoor cabinetry, dining table",
    finish: "Weather-resistant oil",
    setting: "Outdoor",
    commonDimensions: "Custom structural timber",
    durability: "High",
    moistureResistance: "Enhanced (exterior-grade finish)",
  },
  {
    id: "jet-lounge-bar",
    image: "/images/gallery/jet-lounge-bar.jpg",
    alt: "Private aviation lounge with mahogany bar cabinetry",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Cabin panelling, bar cabinetry",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom aviation-grade joinery",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "jet-dining",
    image: "/images/gallery/jet-dining.jpg",
    alt: "Private aviation dining cabin with mahogany table",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Dining table, cabin panelling",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom aviation-grade joinery",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "armoire-cabinet",
    image: "/images/gallery/armoire-cabinet.jpg",
    alt: "Hand-carved mahogany armoire cabinet",
    category: "furniture",
    species: "African Mahogany (Khaya)",
    application: "Freestanding cabinet, hand-carved detailing",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom furniture-grade stock",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "yacht-salon",
    image: "/images/gallery/yacht-salon.jpg",
    alt: "Yacht salon interior with mahogany joinery and ocean view",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Salon joinery, cabinetry, flooring",
    finish: "Marine-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom marine joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "sailing-yacht-deck",
    image: "/images/gallery/sailing-yacht-deck.jpg",
    alt: "Sailing yacht foredeck with built-in mahogany seating",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Deck planking, built-in seating",
    finish: "Marine-grade oiled",
    setting: "Outdoor",
    commonDimensions: "20–25mm deck boards",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "pool-deck-palms",
    image: "/images/gallery/pool-deck-palms.jpg",
    alt: "Poolside mahogany decking around a luxury residence",
    category: "decking",
    species: "African Mahogany (Khaya)",
    application: "Pool deck, terrace decking",
    finish: "Weather-resistant oil",
    setting: "Outdoor",
    commonDimensions: "20–25mm deck boards",
    durability: "High",
    moistureResistance: "Enhanced (exterior-grade finish)",
  },
  {
    id: "living-room-shelving",
    image: "/images/gallery/living-room-shelving.jpg",
    alt: "Living room with mahogany shelving and linear fireplace",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Built-in shelving, wall panelling",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "Custom millwork",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "hotel-bar-coffered",
    image: "/images/gallery/hotel-bar-coffered.jpg",
    alt: "Hotel bar with coffered mahogany ceiling and panelling",
    category: "hotels-resorts",
    species: "African Mahogany (Khaya)",
    application: "Coffered ceiling, bar panelling, flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "Custom millwork",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "hotel-lobby-reception",
    image: "/images/gallery/hotel-lobby-reception.jpg",
    alt: "Hotel reception lobby with mahogany panelling and reception desk",
    category: "hotels-resorts",
    species: "African Mahogany (Khaya)",
    application: "Wall panelling, reception desk",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom millwork",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "executive-study",
    image: "/images/gallery/executive-study.jpg",
    alt: "Executive study with mahogany shelving and parquet floor",
    category: "corporate-hq",
    species: "African Mahogany (Khaya)",
    application: "Built-in shelving, desk, parquet flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom millwork",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "formal-dining-chandelier",
    image: "/images/gallery/formal-dining-chandelier.jpg",
    alt: "Formal dining room with mahogany table and herringbone floor",
    category: "fine-dining",
    species: "African Mahogany (Khaya)",
    application: "Dining table, wall panelling, herringbone flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, 38–50mm tabletop",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "living-room-sectional",
    image: "/images/gallery/living-room-sectional.jpg",
    alt: "Living room with full mahogany wall panelling",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Full wall panelling",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "19–25mm panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "living-room-minimal",
    image: "/images/gallery/living-room-minimal.jpg",
    alt: "Minimalist living room with mahogany accent wall",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Accent wall panelling",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "19–25mm panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "bedroom-arched-window",
    image: "/images/gallery/bedroom-arched-window.jpg",
    alt: "Bedroom with mahogany bed frame and herringbone flooring",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Bed frame, nightstands, herringbone flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "home-office-nook",
    image: "/images/gallery/home-office-nook.jpg",
    alt: "Built-in mahogany home office desk and shelving",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Built-in desk, shelving, herringbone flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom millwork",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "round-dining-table",
    image: "/images/gallery/round-dining-table.jpg",
    alt: "Round mahogany dining table with parquet flooring",
    category: "fine-dining",
    species: "African Mahogany (Khaya)",
    application: "Dining table, window frames, parquet flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, 38–50mm tabletop",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "kitchen-burgundy",
    image: "/images/gallery/kitchen-burgundy.jpg",
    alt: "Kitchen with dark mahogany cabinetry and herringbone flooring",
    category: "furniture",
    species: "African Mahogany (Khaya)",
    application: "Kitchen cabinetry, herringbone flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom cabinetry",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "hallway-doors",
    image: "/images/gallery/hallway-doors.jpg",
    alt: "Residential hallway with mahogany door and trim panelling",
    category: "doors-joinery",
    species: "African Mahogany (Khaya)",
    application: "Doors, wall trim, herringbone flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom door frames",
    durability: "High",
    moistureResistance: "Standard interior",
  },

  // --- Lot 3 ---
  {
    id: "dining-room-arched-windows",
    image: "/images/gallery/dining-room-arched-windows.jpg",
    alt: "Grand dining room with mahogany table beneath arched windows",
    category: "fine-dining",
    species: "African Mahogany (Khaya)",
    application: "Dining table, sideboard, herringbone flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, 38–50mm tabletop",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "billiards-room",
    image: "/images/gallery/billiards-room.jpg",
    alt: "Billiards room with mahogany panelling and herringbone floor",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Wall panelling, herringbone flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, 19–25mm panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "hotel-corridor-piano",
    image: "/images/gallery/hotel-corridor-piano.jpg",
    alt: "Hotel corridor with mahogany panelling and parquet flooring",
    category: "hotels-resorts",
    species: "African Mahogany (Khaya)",
    application: "Wall panelling, parquet flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, 19–25mm panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "bedroom-carved-bed",
    image: "/images/gallery/bedroom-carved-bed.jpg",
    alt: "Bedroom with hand-carved mahogany bed frame and herringbone floor",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Bed frame, wall panelling, herringbone flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom furniture-grade stock",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "grand-parlor",
    image: "/images/gallery/grand-parlor.jpg",
    alt: "Grand parlor with full mahogany wall panelling and parquet floor",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Full wall panelling, parquet flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, 19–25mm panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "living-room-mantel",
    image: "/images/gallery/living-room-mantel.jpg",
    alt: "Living room with mahogany fireplace mantel wall and parquet floor",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Fireplace wall panelling, parquet flooring",
    finish: "Gloss lacquer",
    setting: "Indoor",
    commonDimensions: "14mm flooring, 19–25mm panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "library-tall-shelving",
    image: "/images/gallery/library-tall-shelving.jpg",
    alt: "Floor-to-ceiling mahogany library shelving",
    category: "interior-design",
    species: "African Mahogany (Khaya)",
    application: "Built-in shelving, flooring",
    finish: "Satin lacquer",
    setting: "Indoor",
    commonDimensions: "Custom millwork",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "bathroom-vanity-chevron",
    image: "/images/gallery/bathroom-vanity-chevron.jpg",
    alt: "Modern bathroom with mahogany vanity and chevron flooring",
    category: "luxury-residences",
    species: "African Mahogany (Khaya)",
    application: "Vanity cabinetry, chevron flooring",
    finish: "Marine-grade lacquer (vanity), satin (floor)",
    setting: "Indoor",
    commonDimensions: "14mm flooring, custom cabinetry",
    durability: "High",
    moistureResistance: "Enhanced (wet-area finish)",
  },

  // --- Lot 4 ---
  {
    id: "private-jet-cabin-view",
    image: "/images/gallery/private-jet-cabin-view.jpg",
    alt: "Private jet cabin with mahogany veneer paired with leather seating",
    category: "private-jets",
    species: "African Mahogany (Khaya)",
    application: "Cabin joinery, veneer panelling, cabinetry",
    finish: "Aviation-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Aviation-certified veneer panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "private-jet-galley-bar",
    image: "/images/gallery/private-jet-galley-bar.jpg",
    alt: "Private jet galley and bar unit in high-gloss mahogany veneer",
    category: "private-jets",
    species: "African Mahogany (Khaya)",
    application: "Galley cabinetry, bar unit, countertop surround",
    finish: "Aviation-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Aviation-certified veneer cabinetry",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "private-jet-conference-table",
    image: "/images/gallery/private-jet-conference-table.jpg",
    alt: "Private jet onboard conference table in solid mahogany",
    category: "private-jets",
    species: "African Mahogany (Khaya)",
    application: "Conference table, side cabinetry",
    finish: "Aviation-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom aviation joinery",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "private-jet-bedroom-suite",
    image: "/images/gallery/private-jet-bedroom-suite.jpg",
    alt: "Private jet bedroom suite with mahogany panelling and built-in shelving",
    category: "private-jets",
    species: "African Mahogany (Khaya)",
    application: "Wall panelling, built-in shelving, headboard surround",
    finish: "Aviation-grade satin lacquer",
    setting: "Indoor",
    commonDimensions: "Aviation-certified veneer panelling",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "private-jet-dining-burlwood",
    image: "/images/gallery/private-jet-dining-burlwood.jpg",
    alt: "Private jet dining table in figured mahogany veneer",
    category: "private-jets",
    species: "African Mahogany (Khaya)",
    application: "Dining table, side console",
    finish: "Aviation-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom aviation joinery",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "private-jet-seating-detail",
    image: "/images/gallery/private-jet-seating-detail.jpg",
    alt: "Private jet seating detail beside figured mahogany table",
    category: "private-jets",
    species: "African Mahogany (Khaya)",
    application: "Side table, seat surrounds",
    finish: "Aviation-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom aviation joinery",
    durability: "High",
    moistureResistance: "Standard interior",
  },
  {
    id: "yacht-salon-evening",
    image: "/images/gallery/yacht-salon-evening.jpg",
    alt: "Yacht salon in the evening with mahogany table and cabinetry",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Salon table, wall panelling, cabinetry",
    finish: "Marine-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom marine joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "yacht-cockpit-dusk",
    image: "/images/gallery/yacht-cockpit-dusk.jpg",
    alt: "Yacht cockpit lounge at dusk with teak flooring and mahogany table",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Cockpit table, seating surrounds, decking",
    finish: "Marine-grade satin lacquer",
    setting: "Indoor / Outdoor",
    commonDimensions: "20–25mm deck boards, custom joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "yacht-dining-staircase",
    image: "/images/gallery/yacht-dining-staircase.jpg",
    alt: "Yacht dining area beside a curved mahogany staircase",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Dining table, staircase, wall panelling",
    finish: "Marine-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom marine joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "yacht-saloon-bookshelf",
    image: "/images/gallery/yacht-saloon-bookshelf.jpg",
    alt: "Yacht saloon with built-in mahogany bookshelf and panelling",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Built-in shelving, wall panelling",
    finish: "Marine-grade satin lacquer",
    setting: "Indoor",
    commonDimensions: "Custom marine joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "yacht-corridor-doors",
    image: "/images/gallery/yacht-corridor-doors.jpg",
    alt: "Yacht corridor with mahogany cabin doors and panelling",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Cabin doors, wall panelling, trim",
    finish: "Marine-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom marine joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "yacht-library-office",
    image: "/images/gallery/yacht-library-office.jpg",
    alt: "Yacht library and office nook in mahogany with built-in shelving",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Built-in shelving, desk, wall panelling",
    finish: "Marine-grade satin lacquer",
    setting: "Indoor",
    commonDimensions: "Custom marine joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
  {
    id: "yacht-formal-dining",
    image: "/images/gallery/yacht-formal-dining.jpg",
    alt: "Yacht formal dining table set beneath a mahogany-framed skylight",
    category: "yachts",
    species: "African Mahogany (Khaya)",
    application: "Dining table, ceiling trim, wall panelling",
    finish: "Marine-grade gloss lacquer",
    setting: "Indoor",
    commonDimensions: "Custom marine joinery",
    durability: "High",
    moistureResistance: "High (marine-grade finish)",
  },
];
